name: gomla
description: A new Flutter project.
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.1
  otp_text_field: ^1.1.2
  carousel_slider: ^4.0.0
  provider: ^6.0.2
  http: ^0.13.4
  firebase_messaging: ^11.2.14
  firebase_core: ^1.15.0
  flutter_local_notifications: ^9.4.0
  shared_preferences: ^2.0.13
  geolocator: ^8.2.1
  image_picker: ^0.8.5+3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/splash.png
    - images/backgroundblue.png
    - images/logo.png

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf


